=== Uziel2003/tecweb/practicas/p017/serviciovod_ep.dtd
<!ENTITY % regiones "(MEX|USA|ESP|ARG|KOR)">
<!ELEMENT serviciovod (peliculas, series)>
<!ELEMENT peliculas (video+)>
<!ELEMENT series (video+)>
<!ELEMENT video (titulo, genero, duracion, clasificacion, anio?, temporada?, episodio?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT clasificacion (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT temporada (#PCDATA)>
<!ELEMENT episodio (#PCDATA)>
<!ATTLIST video id CDATA #REQUIRED>
<!ATTLIST peliculas region %regiones; "USA">
<!ATTLIST series region %regiones; "USA">

=== Uziel2003/tecweb/practicas/p017/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviciovod SYSTEM "serviciovod_ep.dtd">
<serviciovod>
    <peliculas region="USA">
        <video id="1">
            <titulo>El Padrino</titulo>
            <genero>Drama</genero>
            <duracion>175</duracion>
            <clasificacion>R</clasificacion>
            <anio>1972</anio>
        </video>
    </peliculas>
    <series region="ESP">
        <video id="3">
            <titulo>La Casa de Papel</titulo>
            <genero>Drama</genero>
            <duracion>45</duracion>
            <clasificacion>TV-MA</clasificacion>
            <temporada>1</temporada>
            <episodio>1</episodio>
        </video>
    </series>
</serviciovod>
